# Generated by Django 4.2.3 on 2023-07-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='is_active',
        ),
    ]
