# Generated by Django 4.2.3 on 2023-08-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address_search',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
