# Generated by Django 4.2.3 on 2024-01-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_remove_restaurant_address_search_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cheapestslice',
            new_name='margharitaindex',
        ),
    ]
